# permissions for end users to edit customapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: custom-application-operator
    app.kubernetes.io/part-of: custom-application-operator
    app.kubernetes.io/managed-by: kustomize
  name: customapplication-editor-role
rules:
- apiGroups:
  - apps.pf93.cn
  resources:
  - customapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.pf93.cn
  resources:
  - customapplications/status
  verbs:
  - get
